# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TG43_2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import TG43

class CloseWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Close")

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(992, 728)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.add_dose_point = QtWidgets.QDialogButtonBox(Dialog)
        self.add_dose_point.setGeometry(QtCore.QRect(9, 115, 80, 25))
        self.add_dose_point.setInputMethodHints(QtCore.Qt.ImhNone)
        self.add_dose_point.setOrientation(QtCore.Qt.Horizontal)
        self.add_dose_point.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.add_dose_point.setCenterButtons(True)
        self.add_dose_point.setObjectName("add_dose_point")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 294, 100))
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.dose_ref_x = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.dose_ref_x.setFont(font)
        self.dose_ref_x.setMouseTracking(False)
        self.dose_ref_x.setAcceptDrops(False)
        self.dose_ref_x.setAutoFillBackground(False)
        self.dose_ref_x.setStyleSheet("")
        self.dose_ref_x.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.dose_ref_x.setAlignment(QtCore.Qt.AlignCenter)
        self.dose_ref_x.setProperty("showGroupSeparator", False)
        self.dose_ref_x.setDecimals(1)
        self.dose_ref_x.setMaximum(1000.0)
        self.dose_ref_x.setSingleStep(0.1)
        self.dose_ref_x.setObjectName("dose_ref_x")
        self.verticalLayout_3.addWidget(self.dose_ref_x)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dose_ref_y = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.dose_ref_y.setFont(font)
        self.dose_ref_y.setMouseTracking(False)
        self.dose_ref_y.setAcceptDrops(False)
        self.dose_ref_y.setAutoFillBackground(False)
        self.dose_ref_y.setStyleSheet("")
        self.dose_ref_y.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.dose_ref_y.setAlignment(QtCore.Qt.AlignCenter)
        self.dose_ref_y.setProperty("showGroupSeparator", False)
        self.dose_ref_y.setDecimals(1)
        self.dose_ref_y.setMaximum(1000.0)
        self.dose_ref_y.setSingleStep(0.1)
        self.dose_ref_y.setObjectName("dose_ref_y")
        self.verticalLayout.addWidget(self.dose_ref_y)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.dose_ref_z = QtWidgets.QDoubleSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.dose_ref_z.setFont(font)
        self.dose_ref_z.setMouseTracking(False)
        self.dose_ref_z.setAcceptDrops(False)
        self.dose_ref_z.setAutoFillBackground(False)
        self.dose_ref_z.setStyleSheet("")
        self.dose_ref_z.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.dose_ref_z.setAlignment(QtCore.Qt.AlignCenter)
        self.dose_ref_z.setProperty("showGroupSeparator", False)
        self.dose_ref_z.setDecimals(1)
        self.dose_ref_z.setMaximum(1000.0)
        self.dose_ref_z.setSingleStep(0.1)
        self.dose_ref_z.setObjectName("dose_ref_z")
        self.verticalLayout_2.addWidget(self.dose_ref_z)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.add_source = QtWidgets.QDialogButtonBox(Dialog)
        self.add_source.setGeometry(QtCore.QRect(10, 440, 80, 25))
        self.add_source.setInputMethodHints(QtCore.Qt.ImhNone)
        self.add_source.setOrientation(QtCore.Qt.Horizontal)
        self.add_source.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.add_source.setCenterButtons(True)
        self.add_source.setObjectName("add_source")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 190, 294, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.source_y = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.source_y.setFont(font)
        self.source_y.setMouseTracking(False)
        self.source_y.setAcceptDrops(False)
        self.source_y.setAutoFillBackground(False)
        self.source_y.setStyleSheet("")
        self.source_y.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.source_y.setAlignment(QtCore.Qt.AlignCenter)
        self.source_y.setProperty("showGroupSeparator", False)
        self.source_y.setDecimals(1)
        self.source_y.setMaximum(1000.0)
        self.source_y.setSingleStep(0.1)
        self.source_y.setObjectName("source_y")
        self.verticalLayout_8.addWidget(self.source_y)
        self.gridLayout.addLayout(self.verticalLayout_8, 4, 1, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_10.addWidget(self.label_10)
        self.source_activity = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.source_activity.setFont(font)
        self.source_activity.setMouseTracking(False)
        self.source_activity.setAcceptDrops(False)
        self.source_activity.setAutoFillBackground(False)
        self.source_activity.setStyleSheet("")
        self.source_activity.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.source_activity.setAlignment(QtCore.Qt.AlignCenter)
        self.source_activity.setProperty("showGroupSeparator", False)
        self.source_activity.setDecimals(1)
        self.source_activity.setMaximum(1000.0)
        self.source_activity.setSingleStep(0.1)
        self.source_activity.setObjectName("source_activity")
        self.verticalLayout_10.addWidget(self.source_activity)
        self.gridLayout.addLayout(self.verticalLayout_10, 2, 0, 1, 3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAutoFillBackground(False)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.source_x = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.source_x.setFont(font)
        self.source_x.setMouseTracking(False)
        self.source_x.setAcceptDrops(False)
        self.source_x.setAutoFillBackground(False)
        self.source_x.setStyleSheet("")
        self.source_x.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.source_x.setAlignment(QtCore.Qt.AlignCenter)
        self.source_x.setProperty("showGroupSeparator", False)
        self.source_x.setDecimals(1)
        self.source_x.setMaximum(1000.0)
        self.source_x.setSingleStep(0.1)
        self.source_x.setObjectName("source_x")
        self.verticalLayout_7.addWidget(self.source_x)
        self.gridLayout.addLayout(self.verticalLayout_7, 4, 0, 1, 1)
        self.source_type = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.source_type.setFont(font)
        self.source_type.setEditable(False)
        self.source_type.setObjectName("source_type")
        self.source_type.addItem("")
        self.source_type.addItem("")
        self.gridLayout.addWidget(self.source_type, 0, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.groupBox_2)
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(5)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 3, 0, 1, 3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_9.addWidget(self.label_9)
        self.source_z = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.source_z.setFont(font)
        self.source_z.setMouseTracking(False)
        self.source_z.setAcceptDrops(False)
        self.source_z.setAutoFillBackground(False)
        self.source_z.setStyleSheet("")
        self.source_z.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.source_z.setAlignment(QtCore.Qt.AlignCenter)
        self.source_z.setProperty("showGroupSeparator", False)
        self.source_z.setDecimals(1)
        self.source_z.setMaximum(1000.0)
        self.source_z.setSingleStep(0.1)
        self.source_z.setObjectName("source_z")
        self.verticalLayout_9.addWidget(self.source_z)
        self.gridLayout.addLayout(self.verticalLayout_9, 4, 2, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_2.setLineWidth(6)
        self.line_2.setMidLineWidth(0)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 3)
        self.source_tree = QtWidgets.QTreeWidget(Dialog)
        self.source_tree.setGeometry(QtCore.QRect(340, 30, 591, 161))
        self.source_tree.setWordWrap(True)
        self.source_tree.setObjectName("source_tree")
        self.source_tree.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.source_tree.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        self.source_tree.headerItem().setTextAlignment(3, QtCore.Qt.AlignCenter)
        self.source_tree.headerItem().setTextAlignment(4, QtCore.Qt.AlignCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.source_tree)
        self.openGLWidget = QtWidgets.QOpenGLWidget(Dialog)
        self.openGLWidget.setGeometry(QtCore.QRect(360, 270, 551, 411))
        self.openGLWidget.setObjectName("openGLWidget")
        self.delete_source = QtWidgets.QPushButton(Dialog)
        self.delete_source.setGeometry(QtCore.QRect(790, 200, 111, 25))
        self.delete_source.setObjectName("delete_source")
        self.close_all = QtWidgets.QDialogButtonBox(Dialog)
        self.close_all.setGeometry(QtCore.QRect(105, 660, 81, 25))
        self.close_all.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.close_all.setObjectName("close_all")

        self.retranslateUi(Dialog)
        self.delete_source.clicked.connect(self.source_tree.clear)
        self.add_dose_point.clicked.connect(self.addRefPoint)
        self.add_source.clicked.connect(self.addSource)
        # self.close_all.clicked.connect(lambda: print("x"))
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.dose_ref_x, self.dose_ref_y)
        Dialog.setTabOrder(self.dose_ref_y, self.dose_ref_z)
        Dialog.setTabOrder(self.dose_ref_z, self.source_type)
        Dialog.setTabOrder(self.source_type, self.source_activity)
        Dialog.setTabOrder(self.source_activity, self.source_x)
        Dialog.setTabOrder(self.source_x, self.source_y)
        Dialog.setTabOrder(self.source_y, self.source_z)
        Dialog.setTabOrder(self.source_z, self.source_tree)

    def addSource(self):
        x, y, z = self.source_x.value(), self.source_y.value(), self.source_z.value()
        activity = self.source_activity.value()
        source = TG43.Source(x, y, z, activity)
        print(source.coordinates)
        print(source.activity)
        print('Source Added')

    def addRefPoint(self):
        x, y, z = self.dose_ref_x.value(), self.dose_ref_y.value(), self.dose_ref_z.value()
        ref = TG43.DoseRefPoint(x, y, z)
        print(ref.cartesian)
        print('Reference Point Added')

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "Add Dose Reference Point"))
        self.label_3.setText(_translate("Dialog", "X (cm)"))
        self.label.setText(_translate("Dialog", "Y (cm)"))
        self.label_2.setText(_translate("Dialog", "Z (cm)"))
        self.groupBox_2.setTitle(_translate("Dialog", "Add Brachy Source"))
        self.label_8.setText(_translate("Dialog", "Y (cm)"))
        self.label_10.setText(_translate("Dialog", "Source Activity (Ci)"))
        self.label_7.setText(_translate("Dialog", "X (cm)"))
        self.source_type.setItemText(0, _translate("Dialog", "Select Source Type"))
        self.source_type.setItemText(1, _translate("Dialog", "Isodose Control HDR 192Ir Flexisource"))
        self.label_9.setText(_translate("Dialog", "Z (cm)"))
        self.source_tree.headerItem().setText(0, _translate("Dialog", "Ref Point"))
        self.source_tree.headerItem().setText(1, _translate("Dialog", "X (cm)"))
        self.source_tree.headerItem().setText(2, _translate("Dialog", "Y (cm)"))
        self.source_tree.headerItem().setText(3, _translate("Dialog", "Z (cm)"))
        self.source_tree.headerItem().setText(4, _translate("Dialog", "Total Dose (cGy)"))
        __sortingEnabled = self.source_tree.isSortingEnabled()
        self.source_tree.setSortingEnabled(False)
        self.source_tree.topLevelItem(0).setText(0, _translate("Dialog", "1"))
        self.source_tree.topLevelItem(0).setText(1, _translate("Dialog", "0"))
        self.source_tree.topLevelItem(0).setText(2, _translate("Dialog", "0"))
        self.source_tree.topLevelItem(0).setText(3, _translate("Dialog", "0"))
        self.source_tree.topLevelItem(0).setText(4, _translate("Dialog", "100"))
        self.source_tree.setSortingEnabled(__sortingEnabled)
        self.delete_source.setText(_translate("Dialog", "Delete Source"))

    def close_window(self):
        self.w = CloseWindow()

